### ISSUE TITLE
Authentication user provider [cognito] is not defined

### ISSUE THREAD

**Issue by GCaplain** [Pod-Point/laravel-cognito-auth#2]
Hi,

I followed your installation instructions and I got this error message, `Authentication user provider [cognito] is not defined`.

What did I forget to do?

**Comment by mikefrancis** [comment]
Hi there,

Did you add the service provider as detailed in the [Installation guide](https://github.com/Pod-Point/laravel-cognito-auth#installation)?

**Comment by GCaplain** [comment]
Yes, I added it in the config.app.php file in the providers array.
I have the problem when I want to use Auth::guest() and Auth::user() in my blade. And strangely, Auth::guest() seems to return false and I am unauthenticated.

**Comment by mikefrancis** [comment]
Very strange, I have just created a fresh install of Laravel, required the package and followed the installation instructions.

`\Auth::guest()` and `\Auth::user()` both work fine in a template, and I don't get the `Authentication user provider [cognito] is not defined.` error.

It sounds like it could possibly be another package or middleware, so it might be worth disabling these one by one until you find the one which is conflicting.

**Comment by GCaplain** [comment]
The error message comes from file `CreateUsersProviders.php` at line 40:

```
public function createUserProvider($provider)
    {
        $config = $this->app['config']['auth.providers.'.$provider];

        if (isset($this->customProviderCreators[$config['driver']])) {
            return call_user_func(
                $this->customProviderCreators[$config['driver']], $this->app, $config
            );
        }

        switch ($config['driver']) {
            case 'database':
                return $this->createDatabaseProvider($config);
            case 'eloquent':
                return $this->createEloquentProvider($config);
            default:
                throw new InvalidArgumentException("Authentication user provider [{$config['driver']}] is not defined.");
        }
    }
```

Is there something I don't understand in the cognito's driver definition procedure ?

**Comment by GCaplain** [comment]
I tried with a fresh installation on homestead environment : 

- `laravel new site` => generated a laravel 5.5 new project named site
- `php artisan key:generate`
- `php artisan make:auth`
- `php artisan migrate`

At this step I have a website with traditionnal authentication. I now want to install laravel-cognito-auth
- "pod-point/laravel-cognito-auth": "^0.1" `in composer.json`
- PodPoint\LaravelCognitoAuth\Providers\CognitoAuthServiceProvider::class in `config/app.php`
- 'driver' => 'cognito', in `auth.php`
- `composer update`
- `php artisan vendor:publish --provider="PodPoint\LaravelCognitoAuth\Providers\CognitoAuthServiceProvider"`
- Add aws configuration in `.env`

Now I reload my website and I have the error : 
`Authentication user provider [cognito] is not defined. (View: /home/vagrant/Code/test/resources/views/layouts/app.blade.php) (View: /home/vagrant/Code/test/resources/views/layouts/app.blade.php)`

I don't know what I do wrong. I wish you could help me.
In any case, thanks for your previous quick responses.

**Comment by j-angnoe** [comment]
Same problem here. Started a new installation, got the `Authentication user provider [cognito] is not defined.`.

In the installation guide you say `update driver in config/auth.php`, currently there are few options for `driver`:

guards.web.driver (== session)
guards.api.driver (== token)

and finally:

providers.users.driver (== cognito)
passwords.users.provider (==users)

Which one of the drivers needs to be set to cognito?
