### ISSUE TITLE
Directly Using

### ISSUE THREAD

**Issue by dave-miller** [Pod-Point/laravel-cognito-auth#3]
Can you provide an example of using 'CognitoClient' directly?

**Comment by threesquared** [comment]
For example you could inject the `CognitoClient` class and call the register method directly:

```php
public function __construct(CognitoClient $client)
{
    $client->register('email@mail.com', 'password');
}
```

**Comment by dave-miller** [comment]
awesome, thank you!

**Comment by threesquared** [comment]
No problem. Closing this issue now.
